### ISSUE TITLE
前端交互逻辑

### ISSUE THREAD

**Issue by rickyyx** [Teched-U/techedu-www#1]
### 上传页面：
视频上传页面应该为单独的一页，用户在上传视频后，此页面应该转换为下一页面（数据展示页面）

客户端Request:
```
url: 'http://35.245.113.215:5000'
files: video 
```

服务器Response: 
```
video_name : `clip.mp4` // 特殊的用来区别video的名字，暂时就用视频原名
video_url: ‘http://35.244.161.66/clip.mp4' // 上传视频的网络缓存 URL
``` 

### 数据展示页面
当用户上传完视频后，服务器会返回一个视频名，并开始处理视频。用户端可通过建立socketIO 来持续获得视频处理的数据。用户端应对这些数据进行展示。
#### 请求的接口（socketIO）：
  - `http://35.245.113.215:5000` ， socketIO的主题为
    - `analysis` （用户端发给服务器）
    - `result` (服务器给用户端） 
#### 数据的格式（例子),  存在`assets/json/clip.json` ：
```
{
    state: 处理完成,
    done: true,
    story_list: [
        {
            "transcript": "This is a sentence",
            "timestamp": 1.3,
            "duration": 6.0,
            "thumbnail": "http://35.244.161.66/thumbnails/clip/0.jpg",
            "words": [
                {
                    "word": "This",
                    "start_time": 1.4,
                    "end_time": 1.9,
                },
                {
                   ... 
                }
            ]
        },
        {...}
    ]
}
```
#### 数据展示设计（草稿）：
处理结果到时候会有多个阶段，每个阶段展示可以做成一个可折叠的模块。
展开的结果显示如果可以的话，或许可以用到material ui 模版中的一些[数据展示模块](https://demos.creative-tim.com/material-dashboard-react/?_ga=2.64778287.189049499.1595105562-237771233.1594009178#/admin/dashboard)

![image](https://user-images.githubusercontent.com/11676094/88004439-0b05dd80-cad5-11ea-87de-37ca696f089f.png)

### 视频展示页面
基于上面的数据，完成2个主要功能：
1. 基于分割好的短视频的跳转功能
   - 在跳转栏中加入缩略图信息
![image](https://user-images.githubusercontent.com/11676094/88002097-aeec8a80-cacf-11ea-94c7-396a4179528d.png)

2. 基于字幕和幻灯片信息的搜索功能

**Comment by rickyyx** [comment]
最新的我的一个更新的代码在branch ： xc上

**Comment by rickyyx** [comment]
### 字幕信息处理

返回数据：
```yaml
{
    done: false,
    id: 1,
    results: {
        avg_seg_dur: x  // 平均长度x
        max_duration: x // 最长片段x秒，
        min_duration: x // 最短片段x秒,
        num_segs: x // 片段数量,
        transcripts : [
            {
                duration: x // 片段长x秒，
                timestamp： x // 片段开始时间x秒,
                transcript: x // 字幕
            }
        ]
    },
    state: “字幕信息处理"
}
```


### 片段整合阶段
```yaml
{
    done: false,
    id: 2,
    results : {
        new_avg_seg_dur: x // 处理后平均时长x秒
        new_num_segs: x // 处理后语句数量
        
        old_avg_seg_dur: x // 处理前平均时长x秒
        old_num_segs: x // 处理前句数量
        histogram : data // historgram数据
    }, 
    state: “片段整合阶段"
}

```

### 短视频分割
```yaml
{
    done: false,
    id: 3,
    results: {
        avg_story_len: x // 短视频平均时长x秒
        num_story： y // 短视频数量

        story_list: [
            {
                duration: x // 短视频长度x秒
                thumbnail： http://xxx.jpg  // 缩略图图片，
                timestamp： x // 短视频开始时间x秒，
                transcript：x // 字幕
                words： []
            }
        ]

    },
    state: “短视频切割"
}

```

### 大纲提取
```yaml
{
    done: true,
    id: 4,
    results: {
        avg_story_len: x // 短视频平均时长x秒
        num_story： y // 短视频数量

        story_list: [
            {
                outline: [
                    {
                        result: {
                            Title: {
                                text: xxxxx,
                                height: x
                                x: 12
                                y : 3
                            } // 标题
                            Subtitle: [] // 副标题
                        },
                        thumbnail: xxxxx
                        timestamp: xx // 时间戳xx秒
                    }
                ]
                duration: x // 短视频长度x秒
                thumbnail： http://xxx.jpg  // 缩略图图片，
                timestamp： x // 短视频开始时间x秒，
                transcript：x // 字幕
                words： []
            }
        ]

    }
}

```
